# Generated by Django 3.0.8 on 2020-08-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=200)),
                ('event_id', models.CharField(default='', max_length=200)),
                ('summary', models.CharField(default='', max_length=200)),
                ('start_dateTime', models.CharField(default='', max_length=200)),
                ('end_dateTime', models.CharField(default='', max_length=200)),
                ('attendee_email', models.CharField(default='', max_length=3000)),
                ('location', models.CharField(default='', max_length=200)),
                ('creator_email', models.CharField(default='', max_length=200)),
                ('organizer_email', models.CharField(default='', max_length=200)),
                ('recurrence', models.CharField(default='', max_length=200)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
